name: 'Diff Files By MD5'
description: 'Check whether two files have the same content by md5'
inputs:
  file1:
    description: 'The first file'
    required: true
  file2:
    description: 'The second file'
    required: true
outputs:
  result:
    description: '"same" or "different"'
    value: ${{ steps.main.outputs.result }}
runs:
  using: "composite"
  steps:
    - id: main
      shell: bash
      run: |
        hash1=`md5sum ${{ inputs.file1 }} | awk '{ print $1 }'`
        hash2=`md5sum ${{ inputs.file2 }} | awk '{ print $1 }'`
        output=`if [ "$hash1" == "$hash2" ]; then echo "same"; else echo "different"; fi`
        echo "::set-output name=result::$output"
